### ISSUE TITLE
Fix the mk_species_index script

### ISSUE THREAD

**Issue by melish** [eaudeweb/percolator#3]
Running `python scripts/mk_species_index` throws an exception caused by `from percolator.conf import settings`. 
This task is to fix the error and update the README with "Initial setup", "Building the index" and "Testing the API" instructions and examples.

**Comment by andrei-duhnea** [comment]
In development environments, the project's directory should be in `PYTHONPATH`. One way to do that is in`.envrc`, so that `direnv` will pick it up upon entering the directory. I've updated the example `.envrc` to show that.
