### ISSUE TITLE
Test extraction on a large annex

### ISSUE THREAD

**Issue by melish** [eaudeweb/percolator#5]
[This document](http://extwprlegs1.fao.org/docs/pdf/cay158894.pdf) includes  a long list of species (> 100 pages) and our aim is to have all of them returned by the tagger.
Let's see the initial results first and then decide how to continue

**Comment by andrei-duhnea** [comment]
Just ran that document a couple of times, extraction takes 3.2-3.5s, resulting in 1139 species and 71 countries.
